application: aileronapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /?
  script: views/index.py
- url: /css
  static_dir: static/css
- url: /img
  static_dir: static/img
- url: /js
  static_dir: static/js
- url: /_admin/load/?
  script: views/admin/load.py
- url: /_admin/update/?
  script: views/admin/update.py
